ARG BASE_DOCKER_IMAGE=nvcr.io/nvidia/pytorch
ARG BASE_DOCKER_TAG=22.11-py3
FROM ${BASE_DOCKER_IMAGE}:${BASE_DOCKER_TAG}

WORKDIR /workspace

#RUN apt update \
#   && apt install -y \
#      python3-pip \
#      python3-venv \
#   && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 --branch master https://github.com/ROCmSoftwarePlatform/transformers \
   && cd /workspace/transformers \
   && pip install wheel \
   && pip install -e . \
   && cd /workspace/transformers/examples/pytorch \
   && sed -i 's/^protobuf$/protobuf <4,>=3.12/' _tests_requirements.txt \
   && pip install -r _tests_requirements.txt

COPY scripts/ scripts
