ARG BASE_DOCKER_IMAGE=nvcr.io/nvidia/pytorch:22.11-py3
FROM ${BASE_DOCKER_IMAGE}
# ARGs need to be reset after a FROM
ARG BASE_DOCKER_IMAGE

ARG TRANSFORMERS_REPO=https://github.com/ROCmSoftwarePlatform/transformers
ARG TRANSFORMERS_BRANCH_OR_TAG=master

WORKDIR /workspace

RUN git clone --depth 1 --branch ${TRANSFORMERS_BRANCH_OR_TAG} ${TRANSFORMERS_REPO} \
   && cd /workspace/transformers \
   && pip install wheel \
   && pip install -e . \
   && cd /workspace/transformers/examples/pytorch \
   && sed -i 's/^protobuf$/protobuf <4,>=3.12/' _tests_requirements.txt \
   && pip install -r _tests_requirements.txt

COPY scripts/ scripts
