# ARG BASE_DOCKER=rocm/pytorch:latest-release
ARG BASE_DOCKER_IMAGE=rocm/pytorch
ARG BASE_DOCKER_TAG=latest-release
FROM ${BASE_DOCKER_IMAGE}:${BASE_DOCKER_TAG}
# FROM rocm/pytorch:${BASE_DOCKER_TAG}

WORKDIR /workspace

RUN git clone --depth 1 --branch master https://github.com/ROCmSoftwarePlatform/transformers \
   && cd /workspace/transformers \
   && pip install -e . \
   && cd /workspace/transformers/examples/pytorch \
   && pip install -r _tests_requirements.txt

COPY scripts/ scripts
